#!/usr/bin/env bash
# Function to display subdomain information
function get_subdomain_info {
  local subdomain=$1
  local domain=$2
  local record_info=$(dig $subdomain.$domain +short)
  if [ -n "$record_info" ]; then
    echo "The subdomain $subdomain is an A record and points to $record_info"
  else
    echo "No record found for $subdomain.$domain"
  fi
}

# Main script logic
domain=$1
subdomain=$2

if [ -z "$domain" ]; then
  echo "Domain is a mandatory parameter"
  exit 1
fi

if [ -z "$subdomain" ]; then
  for sub in www lb-01 web-01 web-02; do
    get_subdomain_info $sub $domain
  done
else
  get_subdomain_info $subdomain $domain
fi
